[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rugbyhrl"
version = "0.1.0"
description = "Basic RugbyHRL project"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Wissam Boussella", email = "wissamboussella@gmail.com" }
]
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.21",
    "pygame>=2.6.1",
]


[tool.setuptools.packages.find]
where = ["src"]
